# every 15 minutes, run `pnpm start` and commit the changes to the repo

name: Generate Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0,15,30,45 * * * *"

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - run: pnpm install

      - name: Generate Feed
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: pnpm start

      - name: Commit Changes
        run: |
          git config --global user.email "me@xangelo.ca"
          git config --global user.name "angelor"
          git commit -am "Update feed"
